// Export Service - Handles 3D model export in multiple formats
import * as THREE from 'three';
import { GCodeSettings } from '../types';
import { validateExportData } from '../utils/inputValidation';

export interface ExportFormat {
  id: string;
  name: string;
  description: string;
  icon: string;
  extension: string;
  requiresSTL?: boolean;
  requiresGeometry?: boolean;
  requiresCode?: boolean;
  needsSettings?: boolean;
}

export class ExportService {

  static exportSTL(stlData: ArrayBuffer, filename: string): void {
    validateExportData('stl', stlData, null, null);
    const blob = new Blob([stlData], { type: 'application/octet-stream' });
    this.downloadBlob(blob, `${filename}.stl`);
  }

  static exportOBJ(geometry: THREE.BufferGeometry, filename: string): void {
    validateExportData('obj', null, geometry, null);

    let objContent = '# OBJ file generated by MORPHOS\n';
    objContent += `o ${filename}\n\n`;

    const positions = geometry.attributes.position.array;
    for (let i = 0; i < positions.length; i += 3) {
      objContent += `v ${positions[i]} ${positions[i + 1]} ${positions[i + 2]}\n`;
    }

    objContent += '\n';

    const vertexCount = positions.length / 3;
    for (let i = 1; i <= vertexCount; i += 3) {
      objContent += `f ${i} ${i + 1} ${i + 2}\n`;
    }

    const blob = new Blob([objContent], { type: 'text/plain' });
    this.downloadBlob(blob, `${filename}.obj`);
  }

  static export3MF(stlData: ArrayBuffer, filename: string): void {
    validateExportData('3mf', stlData, null, null);
    const blob = new Blob([stlData], { type: 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml' });
    this.downloadBlob(blob, `${filename}.3mf`);
  }

  static exportGCODE(geometry: THREE.BufferGeometry, filename: string, settings: Partial<GCodeSettings> = {}): void {
    validateExportData('gcode', null, geometry, null);

    const {
      layerHeight = 0.2,
      nozzleTemp = 200,
      bedTemp = 60,
      printSpeed = 50
    } = settings;

    const gcode = this.generateGCode(filename, { layerHeight, nozzleTemp, bedTemp, printSpeed });
    const blob = new Blob([gcode], { type: 'text/plain' });
    this.downloadBlob(blob, `${filename}.gcode`);
  }

  static exportJSCAD(code: string, filename: string): void {
    validateExportData('jscad', null, null, code);
    const blob = new Blob([code], { type: 'text/javascript' });
    this.downloadBlob(blob, `${filename}.jscad`);
  }

  private static generateGCode(
    filename: string,
    settings: { layerHeight: number; nozzleTemp: number; bedTemp: number; printSpeed: number }
  ): string {
    const { layerHeight, nozzleTemp, bedTemp, printSpeed } = settings;

    return `; GCODE generated by MORPHOS
; Filename: ${filename}
; Layer Height: ${layerHeight}mm
; Nozzle Temperature: ${nozzleTemp}°C
; Bed Temperature: ${bedTemp}°C

; Start GCODE
G28 ; Home all axes
M104 S${nozzleTemp} ; Set nozzle temperature
M140 S${bedTemp} ; Set bed temperature
M109 S${nozzleTemp} ; Wait for nozzle temperature
M190 S${bedTemp} ; Wait for bed temperature
G92 E0 ; Reset extruder
G1 Z2.0 F3000 ; Move Z up
G1 X10 Y10 F5000 ; Move to start position

; Layer 0
G1 Z0.2 F300 ; Move to first layer height
G1 F${printSpeed * 60} ; Set print speed
; Note: Full slicing requires a dedicated slicer
; This is a basic template for demonstration

; End GCODE
G91 ; Relative positioning
G1 E-2 F2700 ; Retract
G1 Z10 F3000 ; Move Z up
G90 ; Absolute positioning
G28 X Y ; Home X and Y
M104 S0 ; Turn off nozzle
M140 S0 ; Turn off bed
M84 ; Disable motors
`;
  }

  private static downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  static getAvailableFormats(): ExportFormat[] {
    return [
      {
        id: 'stl',
        name: 'STL',
        description: 'Standard format for 3D printing',
        icon: 'stl',
        extension: '.stl',
        requiresSTL: true
      },
      {
        id: 'obj',
        name: 'OBJ',
        description: 'Wavefront OBJ format',
        icon: 'obj',
        extension: '.obj',
        requiresGeometry: true
      },
      {
        id: '3mf',
        name: '3MF',
        description: '3D Manufacturing Format',
        icon: '3mf',
        extension: '.3mf',
        requiresSTL: true
      },
      {
        id: 'gcode',
        name: 'GCODE',
        description: 'G-code for 3D printers',
        icon: 'gcode',
        extension: '.gcode',
        requiresGeometry: true,
        needsSettings: true
      },
      {
        id: 'jscad',
        name: 'JSCAD',
        description: 'Source code',
        icon: 'jscad',
        extension: '.jscad',
        requiresCode: true
      }
    ];
  }
}

export default ExportService;
