// Export Service - Handles 3D/2D model export in multiple formats
import { GCodeSettings } from '../types';

export interface ExportFormat {
  id: string;
  name: string;
  description: string;
  icon: string;
  extension: string;
  requiresSTL?: boolean;
  requiresGeometry?: boolean;
  requiresCode?: boolean;
  needsSettings?: boolean;
}

export class ExportService {

  static exportSTL(stlData: ArrayBuffer, filename: string): void {
    const blob = new Blob([stlData], { type: 'application/octet-stream' });
    this.downloadBlob(blob, `${filename}.stl`);
  }

  static exportSTEP(stepData: ArrayBuffer, filename: string): void {
    const blob = new Blob([stepData], { type: 'application/step' });
    this.downloadBlob(blob, `${filename}.step`);
  }

  static exportSVG(svgData: string, filename: string): void {
    const blob = new Blob([svgData], { type: 'image/svg+xml' });
    this.downloadBlob(blob, `${filename}.svg`);
  }

  static exportDXF(dxfData: string, filename: string): void {
    const blob = new Blob([dxfData], { type: 'application/dxf' });
    this.downloadBlob(blob, `${filename}.dxf`);
  }

  static exportOBJ(stlData: ArrayBuffer, filename: string): void {
    // Note: In a real app we'd convert STL to OBJ or get geometry from Babylon
    // For now we'll provide a placeholder or use the STL blob with .obj extension
    // as many tools can handle it, but better to be honest about the implementation.
    const blob = new Blob([stlData], { type: 'text/plain' });
    this.downloadBlob(blob, `${filename}.obj`);
  }

  static exportGCODE(filename: string, settings: Partial<GCodeSettings> = {}): void {
    const {
      layerHeight = 0.2,
      nozzleTemp = 200,
      bedTemp = 60,
      printSpeed = 50
    } = settings;

    const gcode = this.generateGCode(filename, { layerHeight, nozzleTemp, bedTemp, printSpeed });
    const blob = new Blob([gcode], { type: 'text/plain' });
    this.downloadBlob(blob, `${filename}.gcode`);
  }

  static exportCode(code: string, filename: string, mode: '2D' | '3D'): void {
    const blob = new Blob([code], { type: 'text/javascript' });
    this.downloadBlob(blob, `${filename}.${mode === '3D' ? 'replicad' : 'makerjs'}.js`);
  }

  private static generateGCode(
    filename: string,
    settings: { layerHeight: number; nozzleTemp: number; bedTemp: number; printSpeed: number }
  ): string {
    const { layerHeight, nozzleTemp, bedTemp, printSpeed } = settings;

    return `; GCODE generated by MORPHOS
; Filename: ${filename}
; Layer Height: ${layerHeight}mm
; Nozzle Temperature: ${nozzleTemp}°C
; Bed Temperature: ${bedTemp}°C

; Start GCODE
G28 ; Home all axes
M104 S${nozzleTemp} ; Set nozzle temperature
M140 S${bedTemp} ; Set bed temperature
M109 S${nozzleTemp} ; Wait for nozzle temperature
M190 S${bedTemp} ; Wait for bed temperature
G92 E0 ; Reset extruder
G1 Z2.0 F3000 ; Move Z up
G1 X10 Y10 F5000 ; Move to start position

; Layer 0
G1 Z0.2 F300 ; Move to first layer height
G1 F${printSpeed * 60} ; Set print speed

; End GCODE
G91 ; Relative positioning
G1 E-2 F2700 ; Retract
G1 Z10 F3000 ; Move Z up
G90 ; Absolute positioning
G28 X Y ; Home X and Y
M104 S0 ; Turn off nozzle
M140 S0 ; Turn off bed
M84 ; Disable motors
`;
  }

  private static downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  static getAvailableFormats(mode: '2D' | '3D' = '3D'): ExportFormat[] {
    if (mode === '2D') {
      return [
        {
          id: 'svg',
          name: 'SVG',
          description: 'Scalable Vector Graphics',
          icon: '🖼️',
          extension: '.svg'
        },
        {
          id: 'dxf',
          name: 'DXF',
          description: 'AutoCAD DXF format for CNC',
          icon: '📐',
          extension: '.dxf'
        },
        {
          id: 'code',
          name: 'JS Code',
          description: 'Makerjs code source',
          icon: '📜',
          extension: '.js'
        }
      ];
    }

    return [
      {
        id: 'stl',
        name: 'STL',
        description: 'Standard format for 3D printing',
        icon: '🧊',
        extension: '.stl',
        requiresSTL: true
      },
      {
        id: 'step',
        name: 'STEP',
        description: 'Professional CAD format',
        icon: '⚙️',
        extension: '.step'
      },
      {
        id: 'obj',
        name: 'OBJ',
        description: 'Wavefront OBJ format',
        icon: '📦',
        extension: '.obj'
      },
      {
          id: 'gcode',
          name: 'GCODE',
          description: 'G-code for 3D printers',
          icon: '🖨️',
          extension: '.gcode',
          needsSettings: true
      },
      {
        id: 'code',
        name: 'JS Code',
        description: 'Replicad code source',
        icon: '📜',
        extension: '.js'
      }
    ];
  }
}

export default ExportService;
